### PR TITLE
Scale Pages

### PR DESCRIPTION
**Pull request by LaserKaspar**
# Page Scale & Simple Crop

image
image

## What does this do?

It allows users to set a page size (e.g. A4) and a scale. The input document will then be scaled up/down as much as necessary to fit the new page size. After that the scale factor is applied.

## Motivation

I needed to scale multiple PDFs by a factor of 1.2 while maintaining a page size of A4 to get rid of a white border around my PDFs. This change makes it possible, maybe this will help other people too!

Love your project (and your motivation) so far! Keep it up!

### CODE REVIEW

**Comment by Frooodle** [comment]
Love the idea and thanks for contributing to Stirling PDF!

**Comment by Frooodle** [comment]
I would change how the filename is done to use the Util package but i forgot to do that last commit you referred so my bad haha
Will do commit my side to fix that

**Comment by Frooodle** [comment]
image

@LaserKaspar  did minor changes and changed icon
https://github.com/Frooodle/Stirling-PDF/commit/15d39413f36cdd59443965d4510aac8a9e0d1fcf
thanks again!

**Comment by Frooodle** [comment]
Might change description a bit though to me this makes a a4 document 20% larger than a A4 document
Not that it scales the page contents while maintaining the a4 size and hence removing white borders etc

**Comment by Frooodle** [comment]
Yeah thats what i thought, i think we need to change description to better describe it scales contents not the page itself

**Comment by LaserKaspar** [comment]
How about:
"Change the size of page contents while maintaining a set page-size"

**Comment by Frooodle** [comment]
Perfect

**Comment by Frooodle** [comment]
Hi LaserKaspar,

We are updating Stirling-PDF's license to MPL 2.0 (Mozilla Public License Version 2.0) to continue fostering our open-source commitment while introducing more flexible usage of the project.

### What We Need From You:
In order to transition to the MPL 2.0 license, we need the explicit consent of all our contributors. 
1. If you're comfortable relicensing your contributions for this specific PR under MPL 2.0, please respond with:
`
I, LaserKaspar, grant permission to relicense my contributions from this PR to Stirling-PDF under the Mozilla Public License 2.0. 
`
2. If you'd prefer to give blanket permission for all of your contributions to Stirling-PDF (be it through pull requests, commits, or any other form of contribution) rather than on a PR-by-PR basis, please respond with:
`
I, LaserKaspar, grant permission to relicense all my contributions to Stirling-PDF under the Mozilla Public License 2.0.
`

### What does this do and why?
As your old code was contributed under a different license it legally cannot move to a new license without your permission, and since we dont want to lose your code we wanted to reach out. Remember this project is remaining open-source!.

### Deadline:
If we dont receive a response, or if you decline, unfortunately, we will have to remove your contributions from Stirling-PDF before the license change, which is scheduled  in coming months.

### Thank You! 
Your contributions are invaluable, and we hope to continue having them in Stirling-PDF under the new license. Feel free to ask if you have any questions or concerns about this change.

Best,
Frooodle
Stirling-PDF Maintainer

**Comment by Frooodle** [comment]
Hi LaserKaspar,

We are updating Stirling-PDF's license to MPL 2.0 (Mozilla Public License Version 2.0) to continue fostering our open-source commitment while introducing more flexible usage of the project.

### What We Need From You:
In order to transition to the MPL 2.0 license, we need the explicit consent of all our contributors. 
1. If you're comfortable relicensing your contributions for this specific PR under MPL 2.0, please respond with:
`
I, LaserKaspar, grant permission to relicense my contributions from this PR to Stirling-PDF under the Mozilla Public License 2.0. 
`
2. If you'd prefer to give blanket permission for all of your contributions to Stirling-PDF (be it through pull requests, commits, or any other form of contribution) rather than on a PR-by-PR basis, please respond with:
`
I, LaserKaspar, grant permission to relicense all my contributions to Stirling-PDF under the Mozilla Public License 2.0.
`

### What does this do and why?
As your old code was contributed under a different license it legally cannot move to a new license without your permission, and since we dont want to lose your code we wanted to reach out. Remember this project is remaining open-source!.

### Deadline:
If we dont receive a response, or if you decline, unfortunately, we will have to remove your contributions from Stirling-PDF before the license change, which is scheduled  in coming months.

### Thank You! 
Your contributions are invaluable, and we hope to continue having them in Stirling-PDF under the new license. Feel free to ask if you have any questions or concerns about this change.

Best,
Frooodle
Stirling-PDF Maintainer

**Comment by LaserKaspar** [comment]
I, LaserKaspar, grant permission to relicense my contributions from this PR to Stirling-PDF under the Mozilla Public License 2.0.

Keep it up! (:

**Pull request merged**
