### PR TITLE
Add graphics to rotate page

### PR DESCRIPTION
**Pull request by Sf298**
Redesigned the rotate page. Added a complete input form contained within a fragment.

### CODE REVIEW

**Comment by Frooodle** [comment]
Looks awesome! 
I am seeing some bugs though
If you select a PDF, rotate it and save and select another the rotation goes out of allignment 

Also can you fix the sizing so that it shows full horizontal images? instead i am getting
image
(Black is example content, it shows white on the bottom where there is no doc and cuts out rest of page on right)

**Comment by Frooodle** [comment]
This looks awesome though thanks!

**Comment by Sf298** [comment]
@Frooodle I have fixed that bug and a and one other bug that I came across. I also fixed the merge conflicts.

**Comment by Frooodle** [comment]
Hi Sf298,

We are updating Stirling-PDF's license to MPL 2.0 (Mozilla Public License Version 2.0) to continue fostering our open-source commitment while introducing more flexible usage of the project.

### What We Need From You:
In order to transition to the MPL 2.0 license, we need the explicit consent of all our contributors. 
1. If you're comfortable relicensing your contributions for this specific PR under MPL 2.0, please respond with:
`
I, Sf298, grant permission to relicense my contributions from this PR to Stirling-PDF under the Mozilla Public License 2.0. 
`
2. If you'd prefer to give blanket permission for all of your contributions to Stirling-PDF (be it through pull requests, commits, or any other form of contribution) rather than on a PR-by-PR basis, please respond with:
`
I, Sf298, grant permission to relicense all my contributions to Stirling-PDF under the Mozilla Public License 2.0.
`

### What does this do and why?
As your old code was contributed under a different license it legally cannot move to a new license without your permission, and since we dont want to lose your code we wanted to reach out. Remember this project is remaining open-source!.

### Deadline:
If we dont receive a response, or if you decline, unfortunately, we will have to remove your contributions from Stirling-PDF before the license change, which is scheduled  in coming months.

### Thank You! 
Your contributions are invaluable, and we hope to continue having them in Stirling-PDF under the new license. Feel free to ask if you have any questions or concerns about this change.

Best,
Frooodle
Stirling-PDF Maintainer

**Pull request merged**
