### PR TITLE
Bug multitool filename

### PR DESCRIPTION
**Pull request by DimK10**
# License Agreement for Contributions
By submitting this pull request, I acknowledge and agree that my contributions will be included in Stirling-PDF and that they can be relicensed in the future under MPL 2.0 (Mozilla Public License Version 2.0) license. 

(This does not change the general open-source nature of Stirling-PDF, simply moving from one license to another license)

Fixes the issue, by adding a filename input that gets disabled when the used has deleted all pdf files. Also, download button is now disabled if no pdfs are added, or if all pdfs are removed.

### CODE REVIEW

**Comment by DimK10** [comment]
Forgot to add css for light theme for the filename input.

**Comment by Frooodle** [comment]
@DimK10 
Just been testing this,

Is there much benefit of Final name of file: if its always equal to the filename box next to it?
I feel like we should just have a "Resultant filename" entry


Also it might be good to auto fill the first filename to something better than using "managed" when empty, we could default it to first file input or something? Something else anyway

**Comment by DimK10** [comment]
@Frooodle I've made the requested changes! Feel fre to check them out!

**Comment by Frooodle** [comment]
Final change request, to avoid human error, can you add if filename doesnt end in .pdf to readd it

**Comment by DimK10** [comment]
closes #247

**Pull request merged**
