### PR TITLE
Support GitHub Container Registry

### PR DESCRIPTION
**Pull request by pl4nty**
Adds support for GitHub Container Registry to CI/CD and simplifies with third-party Actions.

Third-party runners like [BuildJet](https://buildjet.com) could also be used to speed up ARM builds with [matrix builds](https://github.com/pl4nty/containers/blob/17978f721522fef8ef45f16d02a1e355ac37aadd/.github/workflows/release.yaml#L41-L50).

### CODE REVIEW

**Comment by Frooodle** [comment]
Looks good, let me make my credentials for it later today and then ill merge

**Comment by pl4nty** [comment]
I don't think you'll need creds, just make sure this option is selected on the [settings page](https://github.com/pl4nty/containers/settings/actions)

image

**Comment by Frooodle** [comment]
weird seems it cant grab jar
buildx failed with: ERROR: failed to solve: lstat /tmp/buildkit-mount509811722/build/libs: no such file or directory
not sure why..
I also see it still published a release onto dockerhub regardless

**Comment by Frooodle** [comment]
reverting for now

**Comment by pl4nty** [comment]
@Frooodle whoops, I forgot `context: .` in the buildx action. Otherwise buildx clones its own copy of the repo (designed for running all build steps in Docker).

I've fixed it, added some more features, and [tested successfully](https://github.com/pl4nty/containers/actions/runs/4751067447/jobs/8439832772). I'll submit a new PR soon

**Comment by Frooodle** [comment]
Hi pl4nty,

We are updating Stirling-PDF's license to MPL 2.0 (Mozilla Public License Version 2.0) to continue fostering our open-source commitment while introducing more flexible usage of the project.

### What We Need From You:
In order to transition to the MPL 2.0 license, we need the explicit consent of all our contributors. 
1. If you're comfortable relicensing your contributions for this specific PR under MPL 2.0, please respond with:
`
I, pl4nty, grant permission to relicense my contributions from this PR to Stirling-PDF under the Mozilla Public License 2.0. 
`
2. If you'd prefer to give blanket permission for all of your contributions to Stirling-PDF (be it through pull requests, commits, or any other form of contribution) rather than on a PR-by-PR basis, please respond with:
`
I, pl4nty, grant permission to relicense all my contributions to Stirling-PDF under the Mozilla Public License 2.0.
`

### What does this do and why?
As your old code was contributed under a different license it legally cannot move to a new license without your permission, and since we dont want to lose your code we wanted to reach out. Remember this project is remaining open-source!.

### Deadline:
If we dont receive a response, or if you decline, unfortunately, we will have to remove your contributions from Stirling-PDF before the license change, which is scheduled  in coming months.

### Thank You! 
Your contributions are invaluable, and we hope to continue having them in Stirling-PDF under the new license. Feel free to ask if you have any questions or concerns about this change.

Best,
Frooodle
Stirling-PDF Maintainer

**Comment by pl4nty** [comment]
@Frooodle is there somewhere I can read more about the license change? I'm interested in the reasoning behind the change and future plans, especially the flexible usage you mentioned

**Comment by Frooodle** [comment]
I've not really gone into it much but I realised the current licensing doesn't allow for non GPL code to be part of Stirling-PDF meaning that if I wanted to use any free third party add ons those plugins which I would make optional wouldn't be supported. With the new licencing the repo remains fully open source ( I wouldn't add any pruvate code to the repo) but will allow integration with other plugins if required.

I don't have any plans at moment but there are some good tools out there so its good to use in future.

Additionally it means Stirling-PDF can incorporate other users plugins and a 3rd party system with features that can added or removed outside of initial download

**Comment by Frooodle** [comment]
@pl4nty  let me know if you have any other questions about it

**Comment by pl4nty** [comment]
@Frooodle the GPL allows GPL-compliant libraries/plugins, they don't necessarily have to use GPL - MIT, LGPL, and [many others](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses) are compatible. would that work?

**Comment by Frooodle** [comment]
I have people requesting 3rd party app integration with paid software and special cert signing things etc

I thought it would be nice to allow integration with this software etc and for Stirling-PDF to be able to be legally used by others for their integration purposes of similar nature as well

**Comment by pl4nty** [comment]
Integrating with external apps should be fine, as long as you're not including proprietary software in the Stirling-PDF Docker image. Downstream use of Stirling-PDF is a separate issue, but it's still allowed if they use GPL or a stronger license (eg AGPL).

**Comment by pl4nty** [comment]
You could also create a separate repo under MPL with Stirling-PDF SDKs, generated from the OpenAPI definition. This would allow downstream use with a non-GPL license

**Comment by Frooodle** [comment]
We plan to go the route of external SDKs and such but going with MPL just seems easiest for us certainly because we are also new to open source somewhat and it gives us flexability 

I plan to make the switch next week so please agree/reject as your commit may be removed

**Comment by pl4nty** [comment]
I'm still struggling to understand the reasoning behind the license change, it doesn't seem to be clearly documented anywhere. My contribution is tiny so I'm not super worried, but it's discouraging for future contributions. Are these points accurate?

* Usage of Stirling-PDF as part of closed-source projects
* Third-party code/plugins that aren't GPL-compatible - do you have any examples? most OSS licenses are compatible

**Comment by Frooodle** [comment]
We are exploring the integration of Stirling-PDF with paid services, such as external OCRs, via API keys. Many businesses have expressed a desire for Stirling-PDF to become a comprehensive solution for PDF management, requiring connectivity to specific endpoints or APIs. While RESTful integrations are feasible, some scenarios demand integration with external applications. Under the current GPL license, there are limitations in using non-GPL compliant code, which restricts these integrations.

To address this, we are considering adopting a plugin model. This would allow businesses to develop and share unique plugins for their specific needs. While we intend for any shared plugins to be open and their source viewable, they wouldn't be restricted by the GPL’s copyleft requirements. This ensures that Stirling-PDF remains open-source, but allows for the inclusion of business-specific, possibly non-open-source plugins.

Additionally, the MPL is generally less restrictive compared to GPL. This provides us with more flexibility, particularly in integrating various applications within our Docker containers for the CLI aspect of Stirling-PDF. The goal is to enhance functionality and offer more options to users who prefer such integrations

Lots of OSS apps follow similar plugin model wordpress, eclipse, jenkins, GIMP, VSCode etc with licensed plugins

**Comment by Frooodle** [comment]
Excuse the first two paragraphs being so formal, I have covid so head isnt with it so asked ChatGPT to rewrite it in a clear way for the first two :')

**Comment by pl4nty** [comment]
Makes sense, thanks for the clarification. I, Tom Plant (pl4nty), grant permission to relicense all my contributions to Stirling-PDF under the Mozilla Public License 2.0.

**Pull request merged**
