### PR TITLE
Add side stitch booklet rearrangement

### PR DESCRIPTION
**Pull request by darddan**

### CODE REVIEW

**Comment by darddan** [comment]
Hi, don't know if this will be useful to anyone else. 

The "spine" of the booklets tends to get huge if I print a pdf with a lot of pages in 2 pages per sheet, in both sides of the paper. For such cases the "side stitch" rearrangement works great. 

I didn't see this feature in any of the (popular) pdf tools online.

**Comment by darddan** [comment]
Also, this format will work greatly if the number of pages is a factor of 4. Otherwise it will duplicate the last page until it gets to a factor of 4. It would've been perfect if adding empty pages instead of duplicating would be possible.

**Comment by Frooodle** [comment]
Seems good to me 
I will also add a feature to insert blank pages later

**Comment by Frooodle** [comment]
Hi darddan,

We are updating Stirling-PDF's license to MPL 2.0 (Mozilla Public License Version 2.0) to continue fostering our open-source commitment while introducing more flexible usage of the project.

### What We Need From You:
In order to transition to the MPL 2.0 license, we need the explicit consent of all our contributors. 
1. If you're comfortable relicensing your contributions for this specific PR under MPL 2.0, please respond with:
`
I, darddan, grant permission to relicense my contributions from this PR to Stirling-PDF under the Mozilla Public License 2.0. 
`
2. If you'd prefer to give blanket permission for all of your contributions to Stirling-PDF (be it through pull requests, commits, or any other form of contribution) rather than on a PR-by-PR basis, please respond with:
`
I, darddan, grant permission to relicense all my contributions to Stirling-PDF under the Mozilla Public License 2.0.
`

### What does this do and why?
As your old code was contributed under a different license it legally cannot move to a new license without your permission, and since we dont want to lose your code we wanted to reach out. Remember this project is remaining open-source!.

### Deadline:
If we dont receive a response, or if you decline, unfortunately, we will have to remove your contributions from Stirling-PDF before the license change, which is scheduled  in coming months.

### Thank You! 
Your contributions are invaluable, and we hope to continue having them in Stirling-PDF under the new license. Feel free to ask if you have any questions or concerns about this change.

Best,
Frooodle
Stirling-PDF Maintainer

**Comment by darddan** [comment]
I, darddan, grant permission to relicense my contributions from this PR to Stirling-PDF under the Mozilla Public License 2.0.

**Pull request merged**
